<?php

namespace Modules\AvnChat\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Models\Permission;
use App\Models\Role;
use App\Models\UserRole;
use App\Models\PermissionRole;
use App\Models\AvnMenu;
use App\Models\User;
use App\Models\GeneralSettings;
use App\Models\ModulesSettingsLink;
use Modules\AvnChat\Entities\ChatRoom;
use Modules\AvnChat\Entities\ChatRoomUser;
use Modules\AvnUser\Entities\Profile;
use Illuminate\Support\Facades\Hash;

class AvnChatDatabaseSeeder extends Seeder
{
    public function run()
    {
        $menu_chat = new AvnMenu();
        $menu_chat->label = 'Chat';
        $menu_chat->route_name = 'chat-index';
        $menu_chat->icon = 'uil-comments-alt';
        $menu_chat->module = "AvnChat";
        $menu_chat->save();

        $global_room = new ChatRoom();
        $global_room->name = 'Community';
        $global_room->save();

        $global_room_user = new ChatRoomUser();
        $global_room_user->room_id = 1;
        $global_room_user->user_id = 1;
        $global_room_user->save();


        $user = new User();
        $user->name = 'customer1';
        $user->email = 'customer1@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer1';
        $user->password = Hash::make('customer1');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/1.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer2';
        $user->email = 'customer2@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer2';
        $user->password = Hash::make('customer2');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/2.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer3';
        $user->email = 'customer3@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer3';
        $user->password = Hash::make('customer3');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/3.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer4';
        $user->email = 'customer4@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer4';
        $user->password = Hash::make('customer4');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/4.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer5';
        $user->email = 'customer5@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer5';
        $user->password = Hash::make('customer5');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/5.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer6';
        $user->email = 'customer6@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer6';
        $user->password = Hash::make('customer6');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/6.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer7';
        $user->email = 'customer7@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer7';
        $user->password = Hash::make('customer7');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/7.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer8';
        $user->email = 'customer8@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer8';
        $user->password = Hash::make('customer8');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/8.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer9';
        $user->email = 'customer9@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer9';
        $user->password = Hash::make('customer9');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/9.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer10';
        $user->email = 'customer10@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer10';
        $user->password = Hash::make('customer10');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/10.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer11';
        $user->email = 'customer11@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer11';
        $user->password = Hash::make('customer11');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/11.png';
        $customer->save();

        $user = new User();
        $user->name = 'customer12';
        $user->email = 'customer12@gmail.com';
        $user->type = 'customer';
        $user->username = 'customer12';
        $user->password = Hash::make('customer12');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $customer = new Profile();
        $customer->id = $user->id;
        $customer->gender = 0;
        $customer->money = 0;
        $customer->img = 'storage/app/AvnUser/12.png';
        $customer->save();

        $user = new User();
        $user->name = 'partner13';
        $user->email = 'partner13@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner13';
        $user->password = Hash::make('partner13');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/13.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner14';
        $user->email = 'partner14@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner14';
        $user->password = Hash::make('partner14');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/14.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner15';
        $user->email = 'partner15@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner15';
        $user->password = Hash::make('partner15');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/15.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner16';
        $user->email = 'partner16@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner16';
        $user->password = Hash::make('partner16');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/16.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner17';
        $user->email = 'partner17@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner17';
        $user->password = Hash::make('partner17');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/17.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner18';
        $user->email = 'partner18@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner18';
        $user->password = Hash::make('partner18');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/18.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner19';
        $user->email = 'partner19@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner19';
        $user->password = Hash::make('partner19');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/19.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner20';
        $user->email = 'partner20@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner20';
        $user->password = Hash::make('partner20');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/20.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner21';
        $user->email = 'partner21@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner21';
        $user->password = Hash::make('partner21');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/21.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner22';
        $user->email = 'partner22@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner22';
        $user->password = Hash::make('partner22');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/22.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner23';
        $user->email = 'partner23@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner23';
        $user->password = Hash::make('partner23');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/23.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();

        $user = new User();
        $user->name = 'partner24';
        $user->email = 'partner24@gmail.com';
        $user->type = 'partner';
        $user->username = 'partner24';
        $user->password = Hash::make('partner24');
        $user->save();
        $global_chat_room_user = new ChatRoomUser();
        $global_chat_room_user->user_id = $user->id;
        $global_chat_room_user->room_id = 1;
        $global_chat_room_user->save();
        $partner = new Profile();
        $partner->id = $user->id;
        $partner->gender = 0;
        $partner->money = 0;
        $partner->img = 'storage/app/AvnUser/24.png';
        $partner->save();
        $partner_chat_room = new ChatRoom();
        $partner_chat_room->is_workspace = 1;
        $partner_chat_room->save();
        $partner_chat_room_user = new ChatRoomUser();
        $partner_chat_room_user->user_id = $user->id;
        $partner_chat_room_user->room_id = $partner_chat_room->id;
        $partner_chat_room_user->save();


        $menu = new AvnMenu();
        $menu->label = 'Đặt lịch';
        $menu->route_name = 'list-order';
        $menu->icon = 'mdi mdi-calendar-sync';
        $menu->module = "AvnChat";
        $menu->save();

        $permission1 = new Permission();
        $permission1->route_names = 'list-order, process-order, delete-order';
        $permission1->name = 'Quản lý đặt lịch';
        $permission1->menu_id = $menu->id;
        $permission1->save();

        $pr1 = new PermissionRole();
        $pr1->role_id = 1;
        $pr1->permission_id = $permission1->id;
        $pr1->save();
        $menu = new AvnMenu();

        $menu->label = 'Phiên làm việc';
        $menu->route_name = 'list-session';
        $menu->icon = 'mdi mdi-format-list-checks';
        $menu->module = "AvnChat";
        $menu->save();

        $permission1 = new Permission();
        $permission1->route_names = 'list-session, process-session, delete-session';
        $permission1->name = 'Quản lý phiên';
        $permission1->menu_id = $menu->id;
        $permission1->save();

        $pr1 = new PermissionRole();
        $pr1->role_id = 1;
        $pr1->permission_id = $permission1->id;
        $pr1->save();
    }
}