<?php

namespace Modules\AvnSetting\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Models\Permission;
use App\Models\Role;
use App\Models\UserRole;
use App\Models\PermissionRole;
use App\Models\AvnMenu;
use App\Models\User;
use App\Models\GeneralSettings;
use App\Models\ModulesSettingsLink;
use Modules\AvnSetting\Entities\Navbar;
use Modules\AvnSetting\Entities\Footer;

class AvnSettingDatabaseSeeder extends Seeder
{
    public function run()
    {
        $menu = new AvnMenu();
        $menu->en = 'Page setup';
        $menu->vi = 'Cài đặt trang';
        $menu->ja = 'ページの設定';
        $menu->route_name = 'page-setting';
        $menu->icon = 'mdi mdi-arrange-send-to-back';
        $menu->module = "AvnSetting";
        $menu->save();

        $menu_navbar = new AvnMenu();
        $menu_navbar->en = 'Navigation bar';
        $menu_navbar->vi = 'Thanh điều hướng';
        $menu_navbar->ja = 'ナビゲーションバー';
        $menu_navbar->route_name = 'navbar';
        $menu_navbar->icon = 'uil-rss';
        $menu_navbar->module = "AvnSetting";
        $menu_navbar->parent = $menu->id;
        $menu_navbar->save();

        $menu_footer = new AvnMenu();
        $menu_footer->en = 'Footer';
        $menu_footer->vi = 'Chân trang';
        $menu_footer->ja = 'フッター';
        $menu_footer->route_name = 'footer';
        $menu_footer->icon = 'uil-rss';
        $menu_footer->module = "AvnSetting";
        $menu_footer->parent = $menu->id;
        $menu_footer->save();

        $menu_home = new AvnMenu();
        $menu_home->label = 'Trang chủ';
        $menu_home->en = 'Home page';
        $menu_home->vi = 'Trang chủ';
        $menu_home->ja = 'ホームページ';
        $menu_home->route_name = 'home-seo';
        $menu_home->icon = 'uil-rss';
        $menu_home->module = "AvnSetting";
        $menu_home->parent = $menu->id;
        $menu_home->save();

        $menu_contact = new AvnMenu();
        $menu_contact->label = 'Liên hệ';
        $menu_contact->en = 'Contact';
        $menu_contact->vi = 'Liên hệ';
        $menu_contact->ja = '連絡先';
        $menu_contact->route_name = 'contact-seo';
        $menu_contact->icon = 'uil-rss';
        $menu_contact->module = "AvnSetting";
        $menu_contact->parent = $menu->id;
        $menu_contact->save();

        $menu_contact = new AvnMenu();
        $menu_contact->label = 'Đặt trước';
        $menu_contact->en = 'Booking';
        $menu_contact->vi = 'Đặt trước';
        $menu_contact->ja = '予約';
        $menu_contact->route_name = 'order-chat-seo';
        $menu_contact->icon = 'uil-rss';
        $menu_contact->module = "AvnSetting";
        $menu_contact->parent = $menu->id;
        $menu_contact->save();



        $menu_post = new AvnMenu();
        $menu_post->label = 'Bài viết';
        $menu_post->en = 'Posts';
        $menu_post->vi = 'Bài viết';
        $menu_post->ja = '投稿';
        $menu_post->route_name = 'post-seo';
        $menu_post->icon = 'uil-rss';
        $menu_post->module = "AvnSetting";
        $menu_post->parent = $menu->id;
        $menu_post->save();


        $permission1 = new Permission();
        $permission1->route_names = 'navbar, edit-navbar, store-navbar, update-navbar, delete-navbar, footer, store-footer, update-footer, delete-footer, contact-seo, update-contact-seo, service-seo, update-service-seo, post-seo, update-post-seo, update-footer-des, home-seo, update-home-seo, order-chat-seo, update-order-chat-seo';
        $permission1->name = 'Cài đặt trang';
        $permission1->menu_id = $menu->id;
        $permission1->save();

        $pr1 = new PermissionRole();
        $pr1->role_id = 1;
        $pr1->permission_id = $permission1->id;
        $pr1->save();




        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_seo_title';
        $setting->value = 'Chat App Home';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_seo_description';
        $setting->value = 'Chat online web app make with AvnTech';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_seo_keywords';
        $setting->value = 'Chat online, Transalte, webapp';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_seo_image';
        $setting->value = 'resources/assets/images/logo1.png';
        $setting->save();

        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_title_en';
        $setting->value = 'Responsive Web UI Kit & Dashboard Template';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_title_vi';
        $setting->value = 'Giao diện đáp ứng và mẫu bảng điều khiển';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_title_ja';
        $setting->value = 'レスポンシブWeb UIキット＆ダッシュボードテンプレート';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_description_en';
        $setting->value = 'AvnTech is a fully featured dashboard and admin template comes with tones of well designed UI elements, components, widgets and pages.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_description_vi';
        $setting->value = 'AvnTech là một mẫu bảng điều khiển và giao diện quản trị đầy đủ tính năng đi kèm với rất nhiều thành phần giao diện người dùng, thành phần, tiện ích và trang đã được thiết kế tốt.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_description_ja';
        $setting->value = 'AvnTechは、豊富なデザインされたUI要素、コンポーネント、ウィジェット、ページを備えた完全機能のダッシュボードおよび管理テンプレートです。';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_link';
        $setting->value = 'https://avntech.vn/';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_image_en';
        $setting->value = 'resources/assets/images/startupxx.svg';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_image_vi';
        $setting->value = 'resources/assets/images/startupxx.svg';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_banner_image_ja';
        $setting->value = 'resources/assets/images/startupxx.svg';
        $setting->save();


        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_title_en';
        $setting->value = 'Expert';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_title_vi';
        $setting->value = 'Chuyên gia';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_title_ja';
        $setting->value = 'エキスパート';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_description_en';
        $setting->value = 'Experienced and dedicated experts.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_description_vi';
        $setting->value = 'Những chuyên gia với dày dặn kinh nghiệm và tận tâm với công việc.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_description_ja';
        $setting->value = '経験豊富で献身的な専門家たち.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_image_en';
        $setting->value = 'resources/assets/images/heartCopy3.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_image_vi';
        $setting->value = 'resources/assets/images/heartCopy3.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_partner_image_ja';
        $setting->value = 'resources/assets/images/heartCopy3.png';
        $setting->save();

        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_icon_en';
        $setting->value = 'resources/assets/images/heart.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_icon_vi';
        $setting->value = 'resources/assets/images/heart.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_icon_ja';
        $setting->value = 'resources/assets/images/heart.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_img_en';
        $setting->value = 'resources/assets/images/features-1xp.svg';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_img_vi';
        $setting->value = 'resources/assets/images/features-1xp.svg';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_img_ja';
        $setting->value = 'resources/assets/images/features-1xp.svg';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_title_en';
        $setting->value = "Features you'll love";
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_title_vi';
        $setting->value = "Những tính năng bạn sẽ yêu thích";
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_title_ja';
        $setting->value = "お気に入りの機能";
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_des_en';
        $setting->value = 'AVNTech comes with next generation ui design and have multiple benefits';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_des_vi';
        $setting->value = 'AVNTech đi kèm với thiết kế giao diện người dùng thế hệ tiếp theo và có nhiều lợi ích';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_des_ja';
        $setting->value = 'AVNTechは次世代のUIデザインを採用し、多くの利点があります';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_sub_title_en';
        $setting->value = 'Inbuilt applications and pages';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_sub_title_vi';
        $setting->value = 'Các ứng dụng và trang tích hợp sẵn';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_sub_title_ja';
        $setting->value = '組み込みアプリケーションとページ';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_sub_des_en';
        $setting->value = 'AVNTech comes with a variety of ready-to-use applications and pages that help to speed up the development';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_sub_des_vi';
        $setting->value = 'AVNTech đi kèm với một loạt các ứng dụng và trang sẵn có sẵn giúp tăng tốc quá trình phát triển';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_sub_des_ja';
        $setting->value = 'AVNTechには、開発を加速させるのに役立つさまざまな使いやすいアプリケーションとページが含まれています';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_link';
        $setting->value = 'https://avntech.vn/';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_en_1';
        $setting->value = 'Projects & Tasks';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_vi_1';
        $setting->value = 'Dự án và Nhiệm vụ';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_ja_1';
        $setting->value = 'プロジェクトとタスク';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_en_2';
        $setting->value = 'Ecommerce Application Pages';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_vi_2';
        $setting->value = 'Trang Ứng dụng Thương mại điện tử';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_ja_2';
        $setting->value = 'Eコマースアプリケーションページ';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_en_3';
        $setting->value = 'Profile, pricing, invoice';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_vi_3';
        $setting->value = 'Hồ sơ, bảng giá, hóa đơn';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_ja_3';
        $setting->value = 'プロフィール、価格、請求書 ';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_en_4';
        $setting->value = 'Login, signup, forget password';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_vi_4';
        $setting->value = 'Đăng nhập, Đăng ký, Quên mật khẩu';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'home_feature_list_item_ja_4';
        $setting->value = 'ログイン、サインアップ、パスワードを忘れました ';
        $setting->save();


        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_seo_title';
        $setting->value = 'Bài viết';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_seo_description';
        $setting->value = 'Chia sẻ kinh nghiệm và kiến thức';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_seo_keywords';
        $setting->value = 'Posts, Share, life style';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_seo_image';
        $setting->value = 'resources/assets/images/logo2.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_title_en';
        $setting->value = 'Posts';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_title_vi';
        $setting->value = 'Chia sẻ bài viết';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_title_ja';
        $setting->value = '投稿';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_description_en';
        $setting->value = 'Sharing experiences and knowledge';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_description_vi';
        $setting->value = 'Chia sẻ kinh nghiệm và kiến thức';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_description_ja';
        $setting->value = '経験と知識を共有する';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_icon_en';
        $setting->value = 'resources/assets/images/heartCopy.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_icon_vi';
        $setting->value = 'resources/assets/images/heartCopy.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'post_page_icon_ja';
        $setting->value = 'resources/assets/images/heartCopy.png';
        $setting->save();


        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_seo_title';
        $setting->value = 'Contact us';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_seo_description';
        $setting->value = 'Please fill out the following form and we will get back to you shortly. For more information please contact us.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_seo_keywords';
        $setting->value = 'Contact us, Get In Touch';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_seo_image';
        $setting->value = 'resources/assets/images/logo4.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_title_en';
        $setting->value = 'Get In Touch';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_title_vi';
        $setting->value = 'Liên hệ';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_title_ja';
        $setting->value = 'お問い合わせください';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_description_en';
        $setting->value = 'Please fill out the following form and we will get back to you shortly. For more information please contact us.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_description_vi';
        $setting->value = 'Vui lòng điền vào biểu mẫu dưới đây và chúng tôi sẽ liên hệ lại trong thời gian sớm nhất. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_description_ja';
        $setting->value = '以下のフォームにご記入いただきますと、迅速にご連絡させていただきます。詳細については、お問い合わせください。';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_icon_en';
        $setting->value = 'resources/assets/images/heartCopy2.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_icon_vi';
        $setting->value = 'resources/assets/images/heartCopy2.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'contact_page_icon_ja';
        $setting->value = 'resources/assets/images/heartCopy2.png';
        $setting->save();


        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_seo_title';
        $setting->value = 'Đặt trước';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_seo_description';
        $setting->value = 'Vui lòng điền vào biểu mẫu dưới đây và chúng tôi sẽ liên hệ lại trong thời gian sớm nhất. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_seo_keywords';
        $setting->value = 'Booking, Get In Touch';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_seo_image';
        $setting->value = 'resources/assets/images/logo4.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_title_en';
        $setting->value = 'Booking';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_title_vi';
        $setting->value = 'Đặt trước';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_title_ja';
        $setting->value = '予約';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_description_en';
        $setting->value = 'Please fill out the following form and we will get back to you shortly. For more information please contact us.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_description_vi';
        $setting->value = 'Vui lòng điền vào biểu mẫu dưới đây và chúng tôi sẽ liên hệ lại trong thời gian sớm nhất. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi.';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_description_ja';
        $setting->value = '以下のフォームにご記入いただきますと、迅速にご連絡させていただきます。詳細については、お問い合わせください。';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_icon_en';
        $setting->value = 'resources/assets/images/heartCopy2.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_icon_vi';
        $setting->value = 'resources/assets/images/heartCopy2.png';
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'order_chat_page_icon_ja';
        $setting->value = 'resources/assets/images/heartCopy2.png';
        $setting->save();

        $nav = new Navbar();
        $nav->name = 'Pricing';
        $nav->en = 'Pricing';
        $nav->vi = 'Giá';
        $nav->ja = '価格';
        $nav->link = 'service';
        $nav->order = 1;
        $nav->parent_id = 0;
        $nav->save();
        $nav = new Navbar();
        $nav->name = 'Blog';
        $nav->en = 'Blog';
        $nav->vi = 'Blog';
        $nav->ja = 'ブログ';
        $nav->link = 'post';
        $nav->order = 2;
        $nav->parent_id = 0;
        $nav->save();
        $nav = new Navbar();
        $nav->name = 'Contact';
        $nav->en = 'Contact';
        $nav->vi = 'Liên hệ';
        $nav->ja = 'お問い合わせ';
        $nav->link = 'contact';
        $nav->order = 3;
        $nav->parent_id = 0;
        $nav->save();

        $footer_app = new Footer();
        $footer_app->name = 'Chat App';
        $footer_app->parent_id = 0;
        $footer_app->save();
        $footer = new Footer();
        $footer->name = 'Pricing';
        $footer->en = 'Pricing';
        $footer->vi = 'Giá';
        $footer->ja = '価格';
        $footer->link = 'service';
        $footer->parent_id = $footer_app->id;
        $footer->save();
        $footer = new Footer();
        $footer->name = 'Blog';
        $footer->en = 'Blog';
        $footer->vi = 'Blog';
        $footer->ja = 'ブログ';
        $footer->link = 'post';
        $footer->parent_id = $footer_app->id;
        $footer->save();
        $footer = new Footer();
        $footer->name = 'Contact';
        $footer->en = 'Contact';
        $footer->vi = 'Liên hệ';
        $footer->ja = 'お問い合わせ';
        $footer->link = 'contact';
        $footer->parent_id = $footer_app->id;
        $footer->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'footer_description_en';
        $setting->value = trim('AVNTech makes it easier to build better websites with<br>
        great speed. Save hundreds of hours of design<br>
        and development by using it.');
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'footer_description_ja';
        $setting->value = trim('AVNTechは、優れたスピードでより良いウェブサイトを構築するのを簡単にします。それを使用することで、デザインや開発に何百時間もの時間を節約できます。');
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'footer_description_vi';
        $setting->value = trim('AVNTech giúp bạn xây dựng những trang web tốt hơn với tốc độ nhanh hơn. Tiết kiệm hàng trăm giờ thiết kế và phát triển bằng cách sử dụng nó.');
        $setting->save();

        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'social_facebook';
        $setting->value = trim('https://www.facebook.com/');
        $setting->save();
        $setting = new GeneralSettings();
        $setting->key = $setting->key ?? 'social_google';
        $setting->value = trim('https://www.google.com/');
        $setting->save();
    }
}